UBUNTU_VERSION=20.04
PYTHON_VERSION=3.9.7
PYTORCH_VERSION=1.9.1
TORCHVISION_VERSION=0.10.1
TORCHAUDIO_VERSION=0.9.1

docker build \
    --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
    --build-arg PYTHON_VERSION=${PYTHON_VERSION} \
    --build-arg PYTORCH_VERSION=${PYTORCH_VERSION} \
    --build-arg TORCHVISION_VERSION=${TORCHVISION_VERSION} \
    --build-arg TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION} \
    -t yuhaow/pytorch:${PYTORCH_VERSION}-py${PYTHON_VERSION}-ubuntu${UBUNTU_VERSION} \
    -f docker/ubuntu/Dockerfile \
    .
