#!/bin/sh

export UBUNTU_VERSION=18.04
export CUDA_VERSION=10.0
export CUDNN_VERSION=7

export PYTHON_VERSION=3.7.12

export PYTORCH_VERSION=1.2.0
export PYTORCH_VERSION_SUFFIX=
export TORCHVISION_VERSION=0.5.0
export TORCHVISION_VERSION_SUFFIX=
export TORCHAUDIO_VERSION=
export TORCHAUDIO_VERSION_SUFFIX=
export PYTORCH_DOWNLOAD_URL=

./docker/ubuntu-cuda/build.sh
